# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 4  
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag  }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.image.containerPort }}
        readinessProbe:
          httpGet:
            path: /customer/ping          # Endpoint to check for readiness (adjust according to your app)
            port: 8080
          initialDelaySeconds: 20    # Wait 20 seconds before the first probe
          periodSeconds: 5         # Probe every 5 seconds
          timeoutSeconds: 2         # Timeout if the probe takes longer than 2 seconds
          failureThreshold: 3       # Mark the Pod as not ready after 3 consecutive failures        
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.image.containerPort }}
  selector:
    app: {{ .Chart.Name }}
