name: Build and Deploy to EKS

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted  # Make sure your EC2 runner is properly registered

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Amazon ECR
      env:
        AWS_REGION: us-east-2  # Change to your region
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 229531317213.dkr.ecr.$AWS_REGION.amazonaws.com

    - name: Build Docker image
      run: |
        docker build -t customer:1 .

    - name: Tag and Push to ECR
      env:
        AWS_REGION: us-east-2
      run: |
        IMAGE_URI=229531317213.dkr.ecr.$AWS_REGION.amazonaws.com/customer:1
        docker tag customer:1 $IMAGE_URI
        docker push $IMAGE_URI

    - name: Update kubeconfig
      run: aws eks --region us-east-2 update-kubeconfig --name batch23-eks-cluster

    - name: Deploy with Helm
      run: |
        helm upgrade --install my-release ./helm-chart --namespace default \
          --set image.repository=229531317213.dkr.ecr.us-east-1.amazonaws.com/customer \
          --set image.tag=1
